const mediaConf = {
  MEDIA_WIDTH_MIN: `380px`,
  MEDIA_WIDTH_MAX: `9999px`,

  MEDIA_WIDTH_MOBILE_MIN: `0px`,
  MEDIA_WIDTH_MOBILE_MAX: `768px - 1px`,

  MEDIA_WIDTH_TABLET_MIN: `768px - 1px`,
  MEDIA_WIDTH_TABLET_MAX: `1025px - 1px`,

  MEDIA_WIDTH_DESKTOP: `1025px - 1px`,
  MEDIA_WIDTH_DESKTOP_MAX: `9999px`,

  MEDIA_WIDTH_DESKTOP_CONTENT: `1440px`,
  MEDIA_WIDTH_DESKTOP_CONTENT_PADDING: `6vw`,


  LAYOUT_DEFAULT_Z_INDEX: `999`,
  COMPONENT_DEFAULT_Z_INDEX: `100`,
};

export default mediaConf;
