import ImgSlide from './Images/imgMenu.png';

const KakaoMapAPI = window.kakao.maps;

const partnersInfo = [
  {
    storeName: '고레카레',
    storeAddress: '사임당로 175 101호',
    menuName: '부타돈 & 가츠돈',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49294, 127.02866),
  },
  {
    storeName: '곤들애',
    storeAddress: '서초구 서초대로78길 46',
    menuName: '곤드레 비빔밥',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49358, 127.02859),
  },
  {
    storeName: '나주가',
    storeAddress: '역삼동 827-47',
    menuName: '곰탕',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49708, 127.03149),
  },
  {
    storeName: '노리 테이블',
    storeAddress: '	테헤란로 142',
    menuName: '가라아게 덮밥',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49968, 127.03492),
  },
  {
    storeName: '더샾샐러드',
    storeAddress: '역삼동 826-37 쌍용플레티넘벨류',
    menuName: '닭가슴살 샐러드',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.4954, 127.03041),
  },
  {
    storeName: '딥커리',
    storeAddress: '역삼동 826-37 쌍용플레티넘벨류 상가',
    menuName: '고로케커리',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.4954, 127.03041),
  },
  {
    storeName: '바니커피',
    storeAddress: '역삼동 826-37 쌍용플레티넘벨류',
    menuName: '와플&커피',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.4954, 127.03041),
  },
  {
    storeName: '반랑',
    storeAddress: '역삼동 827-47',
    menuName: '반미샌드위치',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49708, 127.03149),
  },
  {
    storeName: '봉된장',
    storeAddress: '테헤란로 10길 25',
    menuName: '된장찌개',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49755, 127.03296),
  },
  {
    storeName: '심플한식',
    storeAddress: '서울 강남구 대치동 936-11',
    menuName: '제육도시락',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49775, 127.0534),
  },
  {
    storeName: '양대창',
    storeAddress: '서초구 서초대로 78길 52',
    menuName: '대창덮밥',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49318, 127.02868),
  },
  {
    storeName: '예그리나',
    storeAddress: '서초구 서초대로 74길 49',
    menuName: '샌드위치&커피',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49337, 127.02812),
  },
  {
    storeName: '와플엘리',
    storeAddress: '서울특별시 강남구 테헤란로4길 46',
    menuName: '와플2p+커피',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49533, 127.03037),
  },
  {
    storeName: '유부남',
    storeAddress: '역삼동 826-37 쌍용플레티넘벨류',
    menuName: '유부남 초밥2p+샐러드',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.4954, 127.03041),
  },
  {
    storeName: '질할브로스',
    storeAddress: '테헤란로 151(역삼동)',
    menuName: '치킨오버라이스',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.50094, 127.03612),
  },
  {
    storeName: '청담 돈가스',
    storeAddress: '역삼동 826-37 쌍용플레티넘벨류',
    menuName: '치킨마요',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.4954, 127.03041),
  },
  {
    storeName: '한돈애',
    storeAddress: '서초구 서초동 1327-29 서초파라곤',
    menuName: '제육덮밥',
    mainImage: ImgSlide,
    subImage: ImgSlide,
    latlng: new KakaoMapAPI.LatLng(37.49492, 127.02739),
  },
];

export default partnersInfo;
